name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 10

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
        timeout-minutes: 10

      - name: Install dependencies
        run: |
          python -m pip install -c ci-constraints.txt -r test-requirements.txt .
        timeout-minutes: 10

      - name: Test
        run: |
          python -m unittest
        timeout-minutes: 60
